AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 180

Resources:
  myDB:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: todos
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
        
  CreateTodo:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/api/create.handler
      Events:
        apiForLambda:
          Type: Api 
          Properties:
            Path: /create
            Method: post
      Policies:
        DynamoDBWritePolicy:
          TableName: !Ref myDB
            
  GetTodo:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/api/read.handler
      Events:
        apiForLambda:
          Type: Api 
          Properties:
            Path: /get/{id}
            Method: get
      Policies:
        DynamoDBReadPolicy:
          TableName: !Ref myDB
        
  UpdateTodo:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/api/update.handler
      Events:
        UpdateTodo:
          Type: Api
          Properties:
            Path: /update
            Method: put

  DeleteTodo:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/api/delete.handler
      Events:
        DeleteTodo:
          Type: Api
          Properties:
            Path: /delete
            Method: delete